export const REFRESH_DATA = 'REFRESH_DATA';

export const ROOM_INVALID = 'ROOM_INVALID';
export const ROOM_VALID = 'ROOM_VALID';

export const CLIENT_JOIN_ROOM = 'CLIENT_JOIN_ROOM';

export const CONNECT_CLIENT = 'CONNECT_CLIENT';
export const DISCONNECT_CLIENT = 'DISCONNECT_CLIENT';

export const SPAM_WARN_CLIENT = 'SPAM_WARN_CLIENT';

// export const ESTABLISH_CLIENT = "ESTABLISH_CLIENT";
// export const DETATCH_CLIENT = "DETATCH_CLIENT";
// export const KICK_CLIENT = "KICK_CLIENT";

// export const SELECT_TRACKS = "SELECT_TRACKS";
// export const PLAYER_PLAY = "PLAYER_PLAY";
// export const PLAYER_PAUSE = "PLAYER_PAUSE";
// export const PLAYER_NEXT = "PLAYER_NEXT";
// export const PLAYER_STOP = "PLAYER_STOP";
// export const TRACK_SELECTION_ERROR = "TRACK_SELECTION_ERROR";
