export const REFRESH_DATA = 'REFRESH_DATA';

export const ROOM_INVALID = 'ROOM_INVALID';
export const ROOM_VALID = 'ROOM_VALID';

// player controls
export const CLIENT_GAME_STATE_READY = 'CLIENT_GAME_STATE_READY';

export const CLIENT_JOIN_ROOM = 'CLIENT_JOIN_ROOM';
export const CONNECT_CLIENT = 'CONNECT_CLIENT';
export const DISCONNECT_CLIENT = 'DISCONNECT_CLIENT';
export const SPAM_WARN_CLIENT = 'SPAM_WARN_CLIENT';
