export const SET_DEVICE_ID = "SET_DEVICE_ID";
export const SET_ROOM_CODE = "SET_ROOM_CODE";
export const SET_ROOM_CODE_VALIDITY = "SET_ROOM_CODE_VALIDITY";

export const SET_SOCKET_CONNECTED = "SET_SOCKET_CONNECTED";

export const STORE_DATA = "STORE_DATA";

export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

export const RESET_STATE = "RESET_STATE";

export const LEAVE_ROOM = "LEAVE_ROOM";